services:
  traefik:
    image: traefik:v3.1
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # traefik dashboard + API
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro # so it can listen to docker events

  jupyter:
    image: quay.io/jupyter/scipy-notebook:python-3.11
    # remove token for convenience (unsafe)
    # set memory to 2GiB (default=0.5 GiB)
    command: start-notebook.py --IdentityProvider.token='' -ServerApp.root_dir=/home/jovyan/work -ServerApp.max_buffer_size=2147483648
    expose:
      - "8888"
    volumes:
      # only this dir is persisted (everything else, including installed packages, is not!)
      - $HOME/.sandd/jupyter/work:/home/jovyan/work

    # change ownership of volume mount to fix permission denied errors
    user: root # necessary to change ownership at runtime
    environment:
      CHOWN_HOME: yes # change owner to jovyan
      CHOWN_HOME_OPTS: "-R" # recursive

    labels:
      - traefik.enable=true
      - traefik.http.routers.jupyter.rule=Host(`jupyter.sd.test`)
      - traefik.http.routers.jupyter.tls=true

  memos:
    image: neosmemo/memos:0.22
    expose:
      - "5230"
    volumes:
      - $HOME/.sandd/memos:/var/opt/memos

    labels:
      - traefik.enable=true
      - traefik.http.routers.memos.rule=Host(`memos.sd.test`)
      - traefik.http.routers.memos.tls=true
